export interface IngredientItem {
  id: string;
  nameEn: string;
  nameKh: string;
  category: string;
  iconName: string;
  currentStock: number;
  parStock: number;
  defaultUnit: string;
  allowedUnits: string[];
  defaultPrice: number; // USD per default unit
  lowStockThreshold?: number;
  isCustom?: boolean;
  name?: string; // Legacy alias for nameEn + nameKh
  unit?: string; // Legacy alias for defaultUnit
  requestType?: 'glossary' | 'stuff';
}

export interface OrderItem {
  ingredient: IngredientItem;
  quantity: number;
  unit: string;
  pricePerUnit: number;
  totalCost: number;
  supplier?: string;
  notes?: string;
}

export interface CategoryItem {
  id: string;
  nameEn: string;
  nameKh: string;
  iconName: string;
}

export const MARKET_CATEGORIES: CategoryItem[] = [
  { id: 'all', nameEn: 'All Ingredients', nameKh: 'មុខទំនិញទាំងអស់', iconName: 'LayoutGrid' },
  { id: 'Meat & Poultry', nameEn: 'Meat & Poultry', nameKh: 'សាច់ និងបក្សី', iconName: 'Beef' },
  { id: 'Seafood & Fish', nameEn: 'Seafood & Fish', nameKh: 'គ្រឿងសមុទ្រ និងត្រី', iconName: 'Fish' },
  { id: 'Vegetables & Herbs', nameEn: 'Vegetables & Herbs', nameKh: 'បន្លែ និងគ្រឿងទេស', iconName: 'Carrot' },
  { id: 'Sauces & Pantry', nameEn: 'Sauces & Pantry', nameKh: 'គ្រឿងផ្សំ និងទឹកជ្រលក់', iconName: 'Soup' },
  { id: 'Rice & Noodles', nameEn: 'Rice & Noodles', nameKh: 'អង្ករ និងមី/គុយទាវ', iconName: 'Wheat' },
  { id: 'Beverages & Ice', nameEn: 'Beverages & Ice', nameKh: 'ភេសជ្ជៈ និងទឹកកក', iconName: 'GlassWater' },
];

export const STUFF_CATEGORIES: CategoryItem[] = [
  { id: 'all', nameEn: 'All Supplies & Cash', nameKh: 'សម្ភារៈ និងសាច់ប្រាក់ទាំងអស់', iconName: 'LayoutGrid' },
  { id: 'Glassware & Tableware', nameEn: 'Glassware & Tableware', nameKh: 'កែវ និងចានស្លាបព្រា', iconName: 'GlassWater' },
  { id: 'Petty Cash & Tip Advance', nameEn: 'Petty Cash & Tip Advance', nameKh: 'សាច់ប្រាក់ និងប្រាក់រង្វាន់ Tip', iconName: 'DollarSign' },
  { id: 'Kitchen Equipment & Tools', nameEn: 'Kitchen Equipment & Tools', nameKh: 'ឧបករណ៍ផ្ទះបាយ', iconName: 'Wrench' },
  { id: 'Cleaning & Sanitation', nameEn: 'Cleaning & Sanitation', nameKh: 'សម្ភារៈអនាម័យ និងសម្អាត', iconName: 'Sparkles' },
];

export const MARKET_SUPPLIERS = [
  'Morning Wet Market - Vendor A (ផ្សារព្រឹក)',
  'Orussey Wholesale Market (ផ្សារអូរឫស្សី)',
  'Makro Wholesale Cambodia (ម៉ាក្រូ)',
  'Super Duper Direct (ស៊ុបភើរឌូបភើរ)',
  'Local Farm Direct (កសិដ្ឋានក្នុងស្រុក)',
  'Seafood Direct Sihanoukville (គ្រឿងសមុទ្រកំពង់សោម)',
];

export const STUFF_SUPPLIERS = [
  'Internal Cash / Tip Payout (បេឡា / ដកប្រាក់ Tip)',
  'Orussey Restaurant Supply Store (ហាងលក់សម្ភារៈ អូរឫស្សី)',
  'Makro Commercial Equipment (ម៉ាក្រូ សម្ភារៈ)',
  'General Maintenance & Hardware Store (សម្ភារៈជួសជុល និងជាង)',
  'Supermarket Hygiene & Cleaning Direct (សម្ភារៈអនាម័យ)',
];

export const ALL_AVAILABLE_UNITS = [
  'kg',
  'gram',
  'bird',
  'piece',
  'bottle',
  'pack',
  'box',
  'bag'
];

export const ALL_STUFF_UNITS = [
  'piece',
  'set',
  'USD',
  'KHR',
  'box',
  'pack',
  'bottle',
  'gallon',
  'tank',
  'role'
];

export const DEFAULT_MARKET_CATALOG: IngredientItem[] = [
  // Meat & Poultry
  {
    id: 'pork-belly',
    nameEn: 'Pork Belly',
    nameKh: 'សាច់ជ្រូកបីជាន់',
    category: 'Meat & Poultry',
    iconName: 'Beef',
    currentStock: 2,
    parStock: 10,
    defaultUnit: 'kg',
    allowedUnits: ['kg', 'gram', 'piece', 'box'],
    defaultPrice: 5.80,
    lowStockThreshold: 3,
  },
  {
    id: 'ground-pork',
    nameEn: 'Ground Pork',
    nameKh: 'សាច់ជ្រូកចិញ្ច្រាំ',
    category: 'Meat & Poultry',
    iconName: 'Beef',
    currentStock: 5,
    parStock: 12,
    defaultUnit: 'kg',
    allowedUnits: ['kg', 'gram', 'pack'],
    defaultPrice: 4.50,
    lowStockThreshold: 4,
  },
  {
    id: 'chicken-breast',
    nameEn: 'Chicken Breast',
    nameKh: 'ទ្រូងមាន់ស្រស់',
    category: 'Meat & Poultry',
    iconName: 'Utensils',
    currentStock: 12,
    parStock: 15,
    defaultUnit: 'kg',
    allowedUnits: ['kg', 'gram', 'piece', 'box'],
    defaultPrice: 3.80,
    lowStockThreshold: 5,
  },
  {
    id: 'whole-chicken',
    nameEn: 'Whole Chicken',
    nameKh: 'មាន់មូលស្រស់',
    category: 'Meat & Poultry',
    iconName: 'Egg',
    currentStock: 3,
    parStock: 12,
    defaultUnit: 'bird',
    allowedUnits: ['bird', 'kg', 'piece'],
    defaultPrice: 6.50,
    lowStockThreshold: 4,
  },
  {
    id: 'beef-tenderloin',
    nameEn: 'Beef Tenderloin',
    nameKh: 'សាច់គោពិសេស',
    category: 'Meat & Poultry',
    iconName: 'Beef',
    currentStock: 1.5,
    parStock: 6,
    defaultUnit: 'kg',
    allowedUnits: ['kg', 'gram', 'piece'],
    defaultPrice: 12.50,
    lowStockThreshold: 2,
  },
  {
    id: 'fresh-duck',
    nameEn: 'Fresh Duck',
    nameKh: 'ទាស្រស់',
    category: 'Meat & Poultry',
    iconName: 'Utensils',
    currentStock: 2,
    parStock: 8,
    defaultUnit: 'bird',
    allowedUnits: ['bird', 'piece', 'kg'],
    defaultPrice: 7.20,
    lowStockThreshold: 3,
  },

  // Seafood & Fish
  {
    id: 'river-fish',
    nameEn: 'River Fish',
    nameKh: 'ត្រីរៀល / ត្រីទន្លេ',
    category: 'Seafood & Fish',
    iconName: 'Fish',
    currentStock: 3,
    parStock: 10,
    defaultUnit: 'kg',
    allowedUnits: ['kg', 'gram', 'piece'],
    defaultPrice: 4.20,
    lowStockThreshold: 3,
  },
  {
    id: 'tiger-prawns',
    nameEn: 'Tiger Prawns / Shrimp',
    nameKh: 'បង្គាខ្លាស្រស់',
    category: 'Seafood & Fish',
    iconName: 'Fish',
    currentStock: 2,
    parStock: 8,
    defaultUnit: 'kg',
    allowedUnits: ['kg', 'gram', 'box'],
    defaultPrice: 11.00,
    lowStockThreshold: 3,
  },
  {
    id: 'squid-fresh',
    nameEn: 'Fresh Squid',
    nameKh: 'មឹកស្រស់',
    category: 'Seafood & Fish',
    iconName: 'Fish',
    currentStock: 6,
    parStock: 10,
    defaultUnit: 'kg',
    allowedUnits: ['kg', 'gram', 'box'],
    defaultPrice: 7.50,
    lowStockThreshold: 3,
  },
  {
    id: 'mud-crab',
    nameEn: 'Fresh Mud Crab',
    nameKh: 'ក្តាមថ្មស្រស់',
    category: 'Seafood & Fish',
    iconName: 'Fish',
    currentStock: 4,
    parStock: 10,
    defaultUnit: 'kg',
    allowedUnits: ['kg', 'piece'],
    defaultPrice: 14.00,
    lowStockThreshold: 4,
  },

  // Vegetables & Herbs
  {
    id: 'lemongrass',
    nameEn: 'Lemongrass',
    nameKh: 'ស្លឹកគ្រៃស្រស់',
    category: 'Vegetables & Herbs',
    iconName: 'Leaf',
    currentStock: 4,
    parStock: 15,
    defaultUnit: 'kg',
    allowedUnits: ['kg', 'gram', 'piece', 'bag'],
    defaultPrice: 1.50,
    lowStockThreshold: 5,
  },
  {
    id: 'garlic-bulbs',
    nameEn: 'Garlic Bulbs',
    nameKh: 'ខ្ទឹមស',
    category: 'Vegetables & Herbs',
    iconName: 'Carrot',
    currentStock: 3,
    parStock: 10,
    defaultUnit: 'kg',
    allowedUnits: ['kg', 'gram', 'bag', 'box'],
    defaultPrice: 2.20,
    lowStockThreshold: 3,
  },
  {
    id: 'red-shallots',
    nameEn: 'Red Shallots',
    nameKh: 'ខ្ទឹមក្រហម',
    category: 'Vegetables & Herbs',
    iconName: 'Carrot',
    currentStock: 5,
    parStock: 12,
    defaultUnit: 'kg',
    allowedUnits: ['kg', 'gram', 'bag'],
    defaultPrice: 2.80,
    lowStockThreshold: 4,
  },
  {
    id: 'kaffir-lime-leaves',
    nameEn: 'Kaffir Lime Leaves',
    nameKh: 'ស្លឹកក្រូចសើច',
    category: 'Vegetables & Herbs',
    iconName: 'Leaf',
    currentStock: 2,
    parStock: 8,
    defaultUnit: 'bag',
    allowedUnits: ['bag', 'gram', 'piece'],
    defaultPrice: 0.80,
    lowStockThreshold: 3,
  },
  {
    id: 'morning-glory',
    nameEn: 'Morning Glory',
    nameKh: 'ត្រកួនស្រស់',
    category: 'Vegetables & Herbs',
    iconName: 'Leaf',
    currentStock: 10,
    parStock: 25,
    defaultUnit: 'kg',
    allowedUnits: ['kg', 'gram', 'piece', 'bag'],
    defaultPrice: 1.20,
    lowStockThreshold: 8,
  },
  {
    id: 'fresh-lime',
    nameEn: 'Fresh Lime',
    nameKh: 'ក្រូចឆ្មា',
    category: 'Vegetables & Herbs',
    iconName: 'Carrot',
    currentStock: 3,
    parStock: 15,
    defaultUnit: 'kg',
    allowedUnits: ['kg', 'gram', 'piece', 'bag'],
    defaultPrice: 2.50,
    lowStockThreshold: 5,
  },

  // Sauces & Pantry
  {
    id: 'fish-sauce-premium',
    nameEn: 'Premium Fish Sauce',
    nameKh: 'ទឹកត្រីពិសេស',
    category: 'Sauces & Pantry',
    iconName: 'Soup',
    currentStock: 6,
    parStock: 20,
    defaultUnit: 'bottle',
    allowedUnits: ['bottle', 'pack', 'box'],
    defaultPrice: 1.80,
    lowStockThreshold: 6,
  },
  {
    id: 'oyster-sauce',
    nameEn: 'Oyster Sauce',
    nameKh: 'ប្រេងខ្យង',
    category: 'Sauces & Pantry',
    iconName: 'Soup',
    currentStock: 4,
    parStock: 12,
    defaultUnit: 'bottle',
    allowedUnits: ['bottle', 'pack', 'box'],
    defaultPrice: 2.50,
    lowStockThreshold: 4,
  },
  {
    id: 'palm-sugar',
    nameEn: 'Palm Sugar',
    nameKh: 'ស្ករត្នោតធម្មជាតិ',
    category: 'Sauces & Pantry',
    iconName: 'CookingPot',
    currentStock: 5,
    parStock: 15,
    defaultUnit: 'kg',
    allowedUnits: ['kg', 'gram', 'pack', 'bag'],
    defaultPrice: 2.00,
    lowStockThreshold: 5,
  },
  {
    id: 'coconut-milk-can',
    nameEn: 'Coconut Milk',
    nameKh: 'ខ្ទិះដូងកំប៉ុង',
    category: 'Sauces & Pantry',
    iconName: 'Package',
    currentStock: 10,
    parStock: 24,
    defaultUnit: 'box',
    allowedUnits: ['box', 'pack', 'bottle'],
    defaultPrice: 1.40,
    lowStockThreshold: 8,
  },

  // Rice & Noodles
  {
    id: 'jasmine-rice-25kg',
    nameEn: 'Jasmine Rice (25kg)',
    nameKh: 'អង្ករម្លិះលេខ១ (២៥គីឡូ)',
    category: 'Rice & Noodles',
    iconName: 'Wheat',
    currentStock: 1,
    parStock: 6,
    defaultUnit: 'bag',
    allowedUnits: ['bag', 'pack', 'kg'],
    defaultPrice: 22.00,
    lowStockThreshold: 2,
  },
  {
    id: 'rice-noodles-kuyteav',
    nameEn: 'Fresh Rice Noodles',
    nameKh: 'គុយទាវស្រស់',
    category: 'Rice & Noodles',
    iconName: 'Wheat',
    currentStock: 8,
    parStock: 20,
    defaultUnit: 'kg',
    allowedUnits: ['kg', 'gram', 'pack', 'bag'],
    defaultPrice: 1.30,
    lowStockThreshold: 6,
  },
  {
    id: 'egg-noodles-yellow',
    nameEn: 'Yellow Egg Noodles',
    nameKh: 'មីលឿងពិសេស',
    category: 'Rice & Noodles',
    iconName: 'Package',
    currentStock: 15,
    parStock: 30,
    defaultUnit: 'pack',
    allowedUnits: ['pack', 'box', 'kg', 'bag'],
    defaultPrice: 0.90,
    lowStockThreshold: 10,
  },

  // Beverages & Ice
  {
    id: 'drinking-water-case',
    nameEn: 'Drinking Water Case',
    nameKh: 'ទឹកបរិសុទ្ធកេស',
    category: 'Beverages & Ice',
    iconName: 'Droplets',
    currentStock: 5,
    parStock: 20,
    defaultUnit: 'box',
    allowedUnits: ['box', 'pack', 'bottle'],
    defaultPrice: 3.50,
    lowStockThreshold: 6,
  },
  {
    id: 'crushed-ice-sack',
    nameEn: 'Crushed Hygienic Ice',
    nameKh: 'ទឹកកកអនាម័យ',
    category: 'Beverages & Ice',
    iconName: 'GlassWater',
    currentStock: 2,
    parStock: 10,
    defaultUnit: 'bag',
    allowedUnits: ['bag', 'kg', 'box'],
    defaultPrice: 2.00,
    lowStockThreshold: 3,
  },
];

export const DEFAULT_STUFF_CATALOG: IngredientItem[] = [
  // Glassware & Tableware
  {
    id: 'wine-glass-red',
    nameEn: 'Red Wine Glass 450ml',
    nameKh: 'កែវស្រាក្រហមប្រណិត',
    category: 'Glassware & Tableware',
    iconName: 'GlassWater',
    currentStock: 24,
    parStock: 48,
    defaultUnit: 'piece',
    allowedUnits: ['piece', 'box', 'set'],
    defaultPrice: 4.50,
    lowStockThreshold: 12,
    requestType: 'stuff',
  },
  {
    id: 'highball-glass',
    nameEn: 'Highball Drinking Glass 350ml',
    nameKh: 'កែវទឹកក្រឡុក / ទឹកសុទ្ធ',
    category: 'Glassware & Tableware',
    iconName: 'GlassWater',
    currentStock: 30,
    parStock: 60,
    defaultUnit: 'piece',
    allowedUnits: ['piece', 'box', 'set'],
    defaultPrice: 1.80,
    lowStockThreshold: 15,
    requestType: 'stuff',
  },
  {
    id: 'beer-mug-500ml',
    nameEn: 'Chilled Beer Mug 500ml',
    nameKh: 'កែវស្រាបៀរក្រាស់',
    category: 'Glassware & Tableware',
    iconName: 'GlassWater',
    currentStock: 18,
    parStock: 40,
    defaultUnit: 'piece',
    allowedUnits: ['piece', 'box'],
    defaultPrice: 2.50,
    lowStockThreshold: 10,
    requestType: 'stuff',
  },
  {
    id: 'ceramic-plate-main',
    nameEn: 'Ceramic Main Course Plate 28cm',
    nameKh: 'ចានបាយសេរ៉ាមិចធំ',
    category: 'Glassware & Tableware',
    iconName: 'Package',
    currentStock: 20,
    parStock: 50,
    defaultUnit: 'piece',
    allowedUnits: ['piece', 'box', 'set'],
    defaultPrice: 3.80,
    lowStockThreshold: 12,
    requestType: 'stuff',
  },
  {
    id: 'cutlery-set-stainless',
    nameEn: 'Stainless Steel Fork & Spoon Set',
    nameKh: 'ឈុតស្លាបព្រា និងសមប្រណិត',
    category: 'Glassware & Tableware',
    iconName: 'Utensils',
    currentStock: 25,
    parStock: 60,
    defaultUnit: 'set',
    allowedUnits: ['set', 'box', 'piece'],
    defaultPrice: 2.20,
    lowStockThreshold: 15,
    requestType: 'stuff',
  },

  // Petty Cash & Tip Advance
  {
    id: 'tip-payout-advance',
    nameEn: 'Staff Tip Advance Payout',
    nameKh: 'ដកប្រាក់រង្វាន់ Tip មុនកាលកំណត់',
    category: 'Petty Cash & Tip Advance',
    iconName: 'DollarSign',
    currentStock: 1000,
    parStock: 2000,
    defaultUnit: 'USD',
    allowedUnits: ['USD', 'KHR', 'piece'],
    defaultPrice: 50.00,
    lowStockThreshold: 100,
    requestType: 'stuff',
  },
  {
    id: 'petty-cash-emergency',
    nameEn: 'Petty Cash - Urgent Operational Expense',
    nameKh: 'សាច់ប្រាក់បម្រុងបន្ទាន់ / ជួសជុល',
    category: 'Petty Cash & Tip Advance',
    iconName: 'DollarSign',
    currentStock: 500,
    parStock: 1000,
    defaultUnit: 'USD',
    allowedUnits: ['USD', 'KHR'],
    defaultPrice: 30.00,
    lowStockThreshold: 100,
    requestType: 'stuff',
  },
  {
    id: 'register-change-coins',
    nameEn: 'Small Change / Coins for Cashier Register',
    nameKh: 'ប្រាក់អាប់ / ប្រាក់រាយសម្រាប់បេឡា',
    category: 'Petty Cash & Tip Advance',
    iconName: 'DollarSign',
    currentStock: 200,
    parStock: 500,
    defaultUnit: 'pack',
    allowedUnits: ['pack', 'USD'],
    defaultPrice: 100.00,
    lowStockThreshold: 50,
    requestType: 'stuff',
  },
  {
    id: 'gas-tank-refill',
    nameEn: 'Cooking Gas Tank Refill 15kg',
    nameKh: 'បញ្ចូលហ្គាសចម្អិនអាហារ ១៥គីឡូ',
    category: 'Petty Cash & Tip Advance',
    iconName: 'CookingPot',
    currentStock: 2,
    parStock: 6,
    defaultUnit: 'tank',
    allowedUnits: ['tank', 'piece'],
    defaultPrice: 18.00,
    lowStockThreshold: 2,
    requestType: 'stuff',
  },

  // Kitchen Equipment & Tools
  {
    id: 'commercial-blender',
    nameEn: 'Heavy Duty Commercial Bar Blender',
    nameKh: 'ម៉ាស៊ីនក្រឡុកកម្លាំងខ្លាំងប្រចាំបារ',
    category: 'Kitchen Equipment & Tools',
    iconName: 'Wrench',
    currentStock: 1,
    parStock: 3,
    defaultUnit: 'set',
    allowedUnits: ['set', 'piece'],
    defaultPrice: 85.00,
    lowStockThreshold: 1,
    requestType: 'stuff',
  },
  {
    id: 'chef-knife-sharpened',
    nameEn: 'Professional Chef Knife 8"',
    nameKh: 'កាំបិតចុងភៅប្រណិត ៨អ៊ីញ',
    category: 'Kitchen Equipment & Tools',
    iconName: 'Utensils',
    currentStock: 3,
    parStock: 8,
    defaultUnit: 'piece',
    allowedUnits: ['piece', 'set'],
    defaultPrice: 25.00,
    lowStockThreshold: 2,
    requestType: 'stuff',
  },
  {
    id: 'cutting-board-color',
    nameEn: 'Color-Coded Hygienic Cutting Board Set',
    nameKh: 'ជ្រុះហាប់ពណ៌អនាម័យ',
    category: 'Kitchen Equipment & Tools',
    iconName: 'LayoutGrid',
    currentStock: 4,
    parStock: 10,
    defaultUnit: 'set',
    allowedUnits: ['set', 'piece'],
    defaultPrice: 15.00,
    lowStockThreshold: 3,
    requestType: 'stuff',
  },

  // Cleaning & Sanitation
  {
    id: 'dishwashing-liquid-5l',
    nameEn: 'Industrial Dishwashing Liquid 5L',
    nameKh: 'សាប៊ូលាងចានធុងធំ ៥លីត្រ',
    category: 'Cleaning & Sanitation',
    iconName: 'Sparkles',
    currentStock: 4,
    parStock: 12,
    defaultUnit: 'gallon',
    allowedUnits: ['gallon', 'bottle', 'box'],
    defaultPrice: 8.50,
    lowStockThreshold: 3,
    requestType: 'stuff',
  },
  {
    id: 'heavy-duty-trash-bags',
    nameEn: 'Heavy Duty Black Trash Bags XXL',
    nameKh: 'ថង់សម្រាមក្រាស់ធំ',
    category: 'Cleaning & Sanitation',
    iconName: 'Package',
    currentStock: 8,
    parStock: 20,
    defaultUnit: 'pack',
    allowedUnits: ['pack', 'box', 'role'],
    defaultPrice: 4.20,
    lowStockThreshold: 5,
    requestType: 'stuff',
  },
  {
    id: 'microfiber-towels',
    nameEn: 'Microfiber Kitchen Cleaning Towels',
    nameKh: 'កន្សែងជូតសម្អាតផ្ទះបាយ',
    category: 'Cleaning & Sanitation',
    iconName: 'Sparkles',
    currentStock: 12,
    parStock: 30,
    defaultUnit: 'pack',
    allowedUnits: ['pack', 'piece', 'box'],
    defaultPrice: 6.00,
    lowStockThreshold: 6,
    requestType: 'stuff',
  },
];
