export interface IngredientItem {
  id: string;
  name: string;
  category: string;
  iconName: string;
  currentStock: number;
  parStock: number;
  defaultUnit: string;
  allowedUnits: string[];
  defaultPrice: number; // USD per default unit
  lowStockThreshold?: number;
  isCustom?: boolean;
  unit?: string; // Legacy alias for defaultUnit
  requestType?: 'glossary' | 'stuff';
}

export interface OrderItem {
  ingredient: IngredientItem;
  quantity: number;
  unit: string;
  pricePerUnit: number;
  totalCost: number;
  supplier?: string;
  notes?: string;
  supplierNotes?: string;
}

export interface CategoryItem {
  id: string;
  name: string;
  iconName: string;
}

export const MARKET_CATEGORIES: CategoryItem[] = [
  { id: 'all', name: 'All Ingredients', iconName: 'LayoutGrid' },
  { id: 'Meat & Poultry', name: 'Meat & Poultry', iconName: 'Beef' },
  { id: 'Seafood & Fish', name: 'Seafood & Fish', iconName: 'Fish' },
  { id: 'Vegetables & Herbs', name: 'Vegetables & Herbs', iconName: 'Carrot' },
  { id: 'Sauces & Pantry', name: 'Sauces & Pantry', iconName: 'Soup' },
  { id: 'Rice & Noodles', name: 'Rice & Noodles', iconName: 'Wheat' },
  { id: 'Beverages & Ice', name: 'Beverages & Ice', iconName: 'GlassWater' },
];

export const STUFF_CATEGORIES: CategoryItem[] = [
  { id: 'all', name: 'All Supplies & Cash', iconName: 'LayoutGrid' },
  { id: 'Glassware & Tableware', name: 'Glassware & Tableware', iconName: 'GlassWater' },
  { id: 'Petty Cash & Tip Advance', name: 'Petty Cash & Tip Advance', iconName: 'DollarSign' },
  { id: 'Kitchen Equipment & Tools', name: 'Kitchen Equipment & Tools', iconName: 'Wrench' },
  { id: 'Cleaning & Sanitation', name: 'Cleaning & Sanitation', iconName: 'Sparkles' },
];

export const MARKET_SUPPLIERS = [
  'Morning Wet Market - Vendor A (ផ្សារព្រឹក)',
  'Orussey Wholesale Market (ផ្សារអូរឫស្សី)',
  'Makro Wholesale Cambodia (ម៉ាក្រូ)',
  'Super Duper Direct (ស៊ុបភើរឌូបភើរ)',
  'Local Farm Direct (កសិដ្ឋានក្នុងស្រុក)',
  'Seafood Direct Sihanoukville (គ្រឿងសមុទ្រកំពង់សោម)',
];

export const STUFF_SUPPLIERS = [
  'Internal Cash / Tip Payout (បេឡា / ដកប្រាក់ Tip)',
  'Orussey Restaurant Supply Store (ហាងលក់សម្ភារៈ អូរឫស្សី)',
  'Makro Commercial Equipment (ម៉ាក្រូ សម្ភារៈ)',
  'General Maintenance & Hardware Store (សម្ភារៈជួសជុល និងជាង)',
  'Supermarket Hygiene & Cleaning Direct (សម្ភារៈអនាម័យ)',
];

export const ALL_AVAILABLE_UNITS = [
  'kg',
  'gram',
  'bird',
  'piece',
  'bottle',
  'pack',
  'box',
  'bag'
];

export const ALL_STUFF_UNITS = [
  'piece',
  'set',
  'USD',
  'KHR',
  'box',
  'pack',
  'bottle',
  'gallon',
  'tank',
  'role'
];

export const DEFAULT_MARKET_CATALOG: IngredientItem[] = [
  // Meat & Poultry
  {
    id: 'pork-belly',
    name: 'Pork Belly',
    category: 'Meat & Poultry',
    iconName: 'Beef',
    currentStock: 2,
    parStock: 10,
    defaultUnit: 'kg',
    allowedUnits: ['kg', 'gram', 'piece', 'box'],
    defaultPrice: 5.80,
    lowStockThreshold: 3,
  },
  {
    id: 'ground-pork',
    name: 'Ground Pork',
    category: 'Meat & Poultry',
    iconName: 'Beef',
    currentStock: 5,
    parStock: 12,
    defaultUnit: 'kg',
    allowedUnits: ['kg', 'gram', 'pack'],
    defaultPrice: 4.50,
    lowStockThreshold: 4,
  },
  {
    id: 'chicken-breast',
    name: 'Chicken Breast',
    category: 'Meat & Poultry',
    iconName: 'Utensils',
    currentStock: 12,
    parStock: 15,
    defaultUnit: 'kg',
    allowedUnits: ['kg', 'gram', 'piece', 'box'],
    defaultPrice: 3.80,
    lowStockThreshold: 5,
  },
  {
    id: 'whole-chicken',
    name: 'Whole Chicken',
    category: 'Meat & Poultry',
    iconName: 'Egg',
    currentStock: 3,
    parStock: 12,
    defaultUnit: 'bird',
    allowedUnits: ['bird', 'kg', 'piece'],
    defaultPrice: 6.50,
    lowStockThreshold: 4,
  },
  {
    id: 'beef-tenderloin',
    name: 'Beef Tenderloin',
    category: 'Meat & Poultry',
    iconName: 'Beef',
    currentStock: 1.5,
    parStock: 6,
    defaultUnit: 'kg',
    allowedUnits: ['kg', 'gram', 'piece'],
    defaultPrice: 12.50,
    lowStockThreshold: 2,
  },
  {
    id: 'fresh-duck',
    name: 'Fresh Duck',
    category: 'Meat & Poultry',
    iconName: 'Utensils',
    currentStock: 2,
    parStock: 8,
    defaultUnit: 'bird',
    allowedUnits: ['bird', 'piece', 'kg'],
    defaultPrice: 7.20,
    lowStockThreshold: 3,
  },

  // Seafood & Fish
  {
    id: 'river-fish',
    name: 'River Fish',
    category: 'Seafood & Fish',
    iconName: 'Fish',
    currentStock: 3,
    parStock: 10,
    defaultUnit: 'kg',
    allowedUnits: ['kg', 'gram', 'piece'],
    defaultPrice: 4.20,
    lowStockThreshold: 3,
  },
  {
    id: 'tiger-prawns',
    name: 'Tiger Prawns / Shrimp',
    category: 'Seafood & Fish',
    iconName: 'Fish',
    currentStock: 2,
    parStock: 8,
    defaultUnit: 'kg',
    allowedUnits: ['kg', 'gram', 'box'],
    defaultPrice: 11.00,
    lowStockThreshold: 3,
  },
  {
    id: 'squid-fresh',
    name: 'Fresh Squid',
    category: 'Seafood & Fish',
    iconName: 'Fish',
    currentStock: 6,
    parStock: 10,
    defaultUnit: 'kg',
    allowedUnits: ['kg', 'gram', 'box'],
    defaultPrice: 7.50,
    lowStockThreshold: 3,
  },
  {
    id: 'mud-crab',
    name: 'Fresh Mud Crab',
    category: 'Seafood & Fish',
    iconName: 'Fish',
    currentStock: 4,
    parStock: 10,
    defaultUnit: 'kg',
    allowedUnits: ['kg', 'piece'],
    defaultPrice: 14.00,
    lowStockThreshold: 4,
  },

  // Vegetables & Herbs
  {
    id: 'lemongrass',
    name: 'Lemongrass',
    category: 'Vegetables & Herbs',
    iconName: 'Leaf',
    currentStock: 4,
    parStock: 15,
    defaultUnit: 'kg',
    allowedUnits: ['kg', 'gram', 'piece', 'bag'],
    defaultPrice: 1.50,
    lowStockThreshold: 5,
  },
  {
    id: 'garlic-bulbs',
    name: 'Garlic Bulbs',
    category: 'Vegetables & Herbs',
    iconName: 'Carrot',
    currentStock: 3,
    parStock: 10,
    defaultUnit: 'kg',
    allowedUnits: ['kg', 'gram', 'bag', 'box'],
    defaultPrice: 2.20,
    lowStockThreshold: 3,
  },
  {
    id: 'red-shallots',
    name: 'Red Shallots',
    category: 'Vegetables & Herbs',
    iconName: 'Carrot',
    currentStock: 5,
    parStock: 12,
    defaultUnit: 'kg',
    allowedUnits: ['kg', 'gram', 'bag'],
    defaultPrice: 2.80,
    lowStockThreshold: 4,
  },
  {
    id: 'kaffir-lime-leaves',
    name: 'Kaffir Lime Leaves',
    category: 'Vegetables & Herbs',
    iconName: 'Leaf',
    currentStock: 2,
    parStock: 8,
    defaultUnit: 'bag',
    allowedUnits: ['bag', 'gram', 'piece'],
    defaultPrice: 0.80,
    lowStockThreshold: 3,
  },
  {
    id: 'morning-glory',
    name: 'Morning Glory',
    category: 'Vegetables & Herbs',
    iconName: 'Leaf',
    currentStock: 10,
    parStock: 25,
    defaultUnit: 'kg',
    allowedUnits: ['kg', 'gram', 'piece', 'bag'],
    defaultPrice: 1.20,
    lowStockThreshold: 8,
  },
  {
    id: 'fresh-lime',
    name: 'Fresh Lime',
    category: 'Vegetables & Herbs',
    iconName: 'Carrot',
    currentStock: 3,
    parStock: 15,
    defaultUnit: 'kg',
    allowedUnits: ['kg', 'gram', 'piece', 'bag'],
    defaultPrice: 2.50,
    lowStockThreshold: 5,
  },

  // Sauces & Pantry
  {
    id: 'fish-sauce-premium',
    name: 'Premium Fish Sauce',
    category: 'Sauces & Pantry',
    iconName: 'Soup',
    currentStock: 6,
    parStock: 20,
    defaultUnit: 'bottle',
    allowedUnits: ['bottle', 'pack', 'box'],
    defaultPrice: 1.80,
    lowStockThreshold: 6,
  },
  {
    id: 'oyster-sauce',
    name: 'Oyster Sauce',
    category: 'Sauces & Pantry',
    iconName: 'Soup',
    currentStock: 4,
    parStock: 12,
    defaultUnit: 'bottle',
    allowedUnits: ['bottle', 'pack', 'box'],
    defaultPrice: 2.50,
    lowStockThreshold: 4,
  },
  {
    id: 'palm-sugar',
    name: 'Palm Sugar',
    category: 'Sauces & Pantry',
    iconName: 'CookingPot',
    currentStock: 5,
    parStock: 15,
    defaultUnit: 'kg',
    allowedUnits: ['kg', 'gram', 'pack', 'bag'],
    defaultPrice: 2.00,
    lowStockThreshold: 5,
  },
  {
    id: 'coconut-milk-can',
    name: 'Coconut Milk',
    category: 'Sauces & Pantry',
    iconName: 'Package',
    currentStock: 10,
    parStock: 24,
    defaultUnit: 'box',
    allowedUnits: ['box', 'pack', 'bottle'],
    defaultPrice: 1.40,
    lowStockThreshold: 8,
  },

  // Rice & Noodles
  {
    id: 'jasmine-rice-25kg',
    name: 'Jasmine Rice (25kg)',
    category: 'Rice & Noodles',
    iconName: 'Wheat',
    currentStock: 1,
    parStock: 6,
    defaultUnit: 'bag',
    allowedUnits: ['bag', 'pack', 'kg'],
    defaultPrice: 22.00,
    lowStockThreshold: 2,
  },
  {
    id: 'rice-noodles-kuyteav',
    name: 'Fresh Rice Noodles',
    category: 'Rice & Noodles',
    iconName: 'Wheat',
    currentStock: 8,
    parStock: 20,
    defaultUnit: 'kg',
    allowedUnits: ['kg', 'gram', 'pack', 'bag'],
    defaultPrice: 1.30,
    lowStockThreshold: 6,
  },
  {
    id: 'egg-noodles-yellow',
    name: 'Yellow Egg Noodles',
    category: 'Rice & Noodles',
    iconName: 'Package',
    currentStock: 15,
    parStock: 30,
    defaultUnit: 'pack',
    allowedUnits: ['pack', 'box', 'kg', 'bag'],
    defaultPrice: 0.90,
    lowStockThreshold: 10,
  },

  // Beverages & Ice
  {
    id: 'drinking-water-case',
    name: 'Drinking Water Case',
    category: 'Beverages & Ice',
    iconName: 'Droplets',
    currentStock: 5,
    parStock: 20,
    defaultUnit: 'box',
    allowedUnits: ['box', 'pack', 'bottle'],
    defaultPrice: 3.50,
    lowStockThreshold: 6,
  },
  {
    id: 'crushed-ice-sack',
    name: 'Crushed Hygienic Ice',
    category: 'Beverages & Ice',
    iconName: 'GlassWater',
    currentStock: 2,
    parStock: 10,
    defaultUnit: 'bag',
    allowedUnits: ['bag', 'kg', 'box'],
    defaultPrice: 2.00,
    lowStockThreshold: 3,
  },
];

export const DEFAULT_STUFF_CATALOG: IngredientItem[] = [
  // Glassware & Tableware
  {
    id: 'wine-glass-red',
    name: 'Red Wine Glass 450ml',
    category: 'Glassware & Tableware',
    iconName: 'GlassWater',
    currentStock: 24,
    parStock: 48,
    defaultUnit: 'piece',
    allowedUnits: ['piece', 'box', 'set'],
    defaultPrice: 4.50,
    lowStockThreshold: 12,
    requestType: 'stuff',
  },
  {
    id: 'highball-glass',
    name: 'Highball Drinking Glass 350ml',
    category: 'Glassware & Tableware',
    iconName: 'GlassWater',
    currentStock: 30,
    parStock: 60,
    defaultUnit: 'piece',
    allowedUnits: ['piece', 'box', 'set'],
    defaultPrice: 1.80,
    lowStockThreshold: 15,
    requestType: 'stuff',
  },
  {
    id: 'beer-mug-500ml',
    name: 'Chilled Beer Mug 500ml',
    category: 'Glassware & Tableware',
    iconName: 'GlassWater',
    currentStock: 18,
    parStock: 40,
    defaultUnit: 'piece',
    allowedUnits: ['piece', 'box'],
    defaultPrice: 2.50,
    lowStockThreshold: 10,
    requestType: 'stuff',
  },
  {
    id: 'ceramic-plate-main',
    name: 'Ceramic Main Course Plate 28cm',
    category: 'Glassware & Tableware',
    iconName: 'Package',
    currentStock: 20,
    parStock: 50,
    defaultUnit: 'piece',
    allowedUnits: ['piece', 'box', 'set'],
    defaultPrice: 3.80,
    lowStockThreshold: 12,
    requestType: 'stuff',
  },
  {
    id: 'cutlery-set-stainless',
    name: 'Stainless Steel Fork & Spoon Set',
    category: 'Glassware & Tableware',
    iconName: 'Utensils',
    currentStock: 25,
    parStock: 60,
    defaultUnit: 'set',
    allowedUnits: ['set', 'box', 'piece'],
    defaultPrice: 2.20,
    lowStockThreshold: 15,
    requestType: 'stuff',
  },

  // Petty Cash & Tip Advance
  {
    id: 'tip-payout-advance',
    name: 'Staff Tip Advance Payout',
    category: 'Petty Cash & Tip Advance',
    iconName: 'DollarSign',
    currentStock: 1000,
    parStock: 2000,
    defaultUnit: 'USD',
    allowedUnits: ['USD', 'KHR', 'piece'],
    defaultPrice: 50.00,
    lowStockThreshold: 100,
    requestType: 'stuff',
  },
  {
    id: 'petty-cash-emergency',
    name: 'Petty Cash - Urgent Operational Expense',
    category: 'Petty Cash & Tip Advance',
    iconName: 'DollarSign',
    currentStock: 500,
    parStock: 1000,
    defaultUnit: 'USD',
    allowedUnits: ['USD', 'KHR'],
    defaultPrice: 30.00,
    lowStockThreshold: 100,
    requestType: 'stuff',
  },
  {
    id: 'register-change-coins',
    name: 'Small Change / Coins for Cashier Register',
    category: 'Petty Cash & Tip Advance',
    iconName: 'DollarSign',
    currentStock: 200,
    parStock: 500,
    defaultUnit: 'pack',
    allowedUnits: ['pack', 'USD'],
    defaultPrice: 100.00,
    lowStockThreshold: 50,
    requestType: 'stuff',
  },
  {
    id: 'gas-tank-refill',
    name: 'Cooking Gas Tank Refill 15kg',
    category: 'Petty Cash & Tip Advance',
    iconName: 'CookingPot',
    currentStock: 2,
    parStock: 6,
    defaultUnit: 'tank',
    allowedUnits: ['tank', 'piece'],
    defaultPrice: 18.00,
    lowStockThreshold: 2,
    requestType: 'stuff',
  },

  // Kitchen Equipment & Tools
  {
    id: 'commercial-blender',
    name: 'Heavy Duty Commercial Bar Blender',
    category: 'Kitchen Equipment & Tools',
    iconName: 'Wrench',
    currentStock: 1,
    parStock: 3,
    defaultUnit: 'set',
    allowedUnits: ['set', 'piece'],
    defaultPrice: 85.00,
    lowStockThreshold: 1,
    requestType: 'stuff',
  },
  {
    id: 'chef-knife-sharpened',
    name: 'Professional Chef Knife 8"',
    category: 'Kitchen Equipment & Tools',
    iconName: 'Utensils',
    currentStock: 3,
    parStock: 8,
    defaultUnit: 'piece',
    allowedUnits: ['piece', 'set'],
    defaultPrice: 25.00,
    lowStockThreshold: 2,
    requestType: 'stuff',
  },
  {
    id: 'cutting-board-color',
    name: 'Color-Coded Hygienic Cutting Board Set',
    category: 'Kitchen Equipment & Tools',
    iconName: 'LayoutGrid',
    currentStock: 4,
    parStock: 10,
    defaultUnit: 'set',
    allowedUnits: ['set', 'piece'],
    defaultPrice: 15.00,
    lowStockThreshold: 3,
    requestType: 'stuff',
  },

  // Cleaning & Sanitation
  {
    id: 'dishwashing-liquid-5l',
    name: 'Industrial Dishwashing Liquid 5L',
    category: 'Cleaning & Sanitation',
    iconName: 'Sparkles',
    currentStock: 4,
    parStock: 12,
    defaultUnit: 'gallon',
    allowedUnits: ['gallon', 'bottle', 'box'],
    defaultPrice: 8.50,
    lowStockThreshold: 3,
    requestType: 'stuff',
  },
  {
    id: 'heavy-duty-trash-bags',
    name: 'Heavy Duty Black Trash Bags XXL',
    category: 'Cleaning & Sanitation',
    iconName: 'Package',
    currentStock: 8,
    parStock: 20,
    defaultUnit: 'pack',
    allowedUnits: ['pack', 'box', 'role'],
    defaultPrice: 4.20,
    lowStockThreshold: 5,
    requestType: 'stuff',
  },
  {
    id: 'microfiber-towels',
    name: 'Microfiber Kitchen Cleaning Towels',
    category: 'Cleaning & Sanitation',
    iconName: 'Sparkles',
    currentStock: 12,
    parStock: 30,
    defaultUnit: 'pack',
    allowedUnits: ['pack', 'piece', 'box'],
    defaultPrice: 6.00,
    lowStockThreshold: 6,
    requestType: 'stuff',
  },
];

export const ALL_CATEGORIES: CategoryItem[] = [
  ...MARKET_CATEGORIES,
  ...STUFF_CATEGORIES.filter(c => c.id !== 'all'),
];

export const ALL_CATALOG: IngredientItem[] = [
  ...DEFAULT_MARKET_CATALOG,
  ...DEFAULT_STUFF_CATALOG,
];
